acl rede_local src 192.168.1.0/24 10.0.0.0/8
acl blocked_sites dstdomain .facebook.com .amazon.com .instagram.com
acl working_hours time MTWHF 08:00-18:00
http_access deny blocked_sites
http_access allow rede_local
delay_pools 3
delay_class 2 3
delay_class 1 2
delay_parameters 1 512000/512000
delay_parameters 2 512000/512000
cache_mem 128 MB
